---
title: "COMP-4442 Final Project"
author: "Zack Larson, Ian McKellar, Suvechhya Pokhrel"
date: "3/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(stringr)
library(plotly)
library(forecast)
library(lubridate)

```

## R Markdown

Data Parsing / Cleanup

```{r}

election_raw <- read.csv('countypres_2000-2020.csv', header = TRUE, sep = ",") #election data

election_raw$state <- as.factor(election_raw$state)
election_raw$county_name <- as.factor(election_raw$county_name)
election_raw$candidate <- as.factor(election_raw$candidate)
election_raw$party <- as.factor(election_raw$party)

election_2020_counties_won <- election_raw %>%
  filter(year == 2020) %>%
  group_by(county_name) %>%
  filter(candidatevotes == max(candidatevotes, na.rm = TRUE)) %>%
  ungroup() # County level results

election_2020 <- election_raw %>% filter(year == 2020) # County level total votes

election_2020_counties_won <- droplevels(election_2020_counties_won)%>%  # Remove unused factors
mutate(fips=county_fips,percVote=100*(candidatevotes/totalvotes))#computing percent of vote for winning party

county_party <- dplyr::select(election_2020_counties_won, fips,party,percVote)
   
#getting rural 
ru = read.csv("https://www.consumerfinance.gov/documents/10338/cfpb_rural-underserved-list_2022.csv")%>% transmute(fips = FIPS.Code, #renaming FIPS.Code to key_numeric
                 countyType = "Rural/Underserved") # creates two vars and drop old vars


```

```{r}
# Loading the covid vaccine data

tscounty <- read.csv("https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=e475ed8fe32f46a5b79815adfab9dae2", sep = ",")
#str(tscounty)

#filtering and cleaning data according to our need

county.vaccine <- dplyr::select(tscounty, date,fips, state, county, actuals.vaccinationsCompleted)%>%
  na.omit(county.vaccine)%>%  #removing all null values from our data
  mutate(date=ymd(date))%>% #converting date column to an actual date format,ymd as it was in ymd format
  filter(date <= "2022-03-01")%>% #we want to see values until first of march as not all counties have reported data after that
  
# Now we have Date, State, County, Cumulative Actual Cases and Vaccination rates grouped by state and county. We can see that the actual cases are cumulative. 
unite("county_state",county:state,remove=FALSE, sep = ",")%>% #combining state and county columns
select(-c(state,county))


#getting new vaccination rates per day using the lag function
vaccine.new <- county.vaccine %>%
  group_by(county_state)%>%
  mutate(new_vacc_rate = actuals.vaccinationsCompleted - lag(actuals.vaccinationsCompleted, default = 0))

```

```{r}
#find the extra fips in new dataset and remove them

fips_to_remove <- unique(ru$fips[!(ru$fips%in%vaccine.new$fips)])
str_c(fips_to_remove)

ru <- ru%>%filter(!fips %in% c(fips_to_remove))


merged <- merge(vaccine.new,ru, by.x = "fips", all= TRUE) # to define NA counties
merged$countyType <- merged$countyType%>% replace_na("Other") # for any county not in the Consumer FIN data replace NA by Other

#find the extra fips in new election dataset and remove them
fips_to_rmv <- unique(county_party$fips[!(county_party$fips%in%vaccine.new$fips)])
str_c(fips_to_rmv)

county_party<-county_party%>%filter(!fips %in% c(fips_to_rmv))

#tsdata will final merge on election data
tsdata <- merge(merged, county_party, by.x = 'fips',all=TRUE)
tsdata$countyType <- as.factor(tsdata$countyType)
str(tsdata)

```




```{r}
library(usmap)

#visualizing the rural and urban counties
plot_usmap(data=tsdata, regions = "counties",values = "countyType")

#visualizing counties with republican vs democratic win
plot_usmap(data=tsdata, regions = "counties", values="party")+
  labs(title="County level Election Results, 2020")

```

```{r}

rural_group <- subset(tsdata, countyType %in% c("Rural/Underserved"))%>%na.omit()
str(rural_group)

#republican party with highest vote percentage

rpr <- rural_group%>%filter(party=="REPUBLICAN")%>%filter(percVote==max(percVote))

#democratic party with highest vote percentage
dpr <- rural_group%>%filter(party== "DEMOCRAT")%>%filter(percVote==max(percVote))


other_group <- subset(tsdata, countyType %in% c("Other"))%>%na.omit()

##republican party with highest vote percentage
rpo <- other_group%>%filter(party=="REPUBLICAN")%>%filter(percVote==max(percVote))
  
#democratic party with highest vote percentage
dpo <- other_group%>%filter(party== "DEMOCRAT")%>%filter(percVote==max(percVote))



#ts analysis

# p<- ggplot(data = fresno_ca,aes(x=date,y=new_vacc_rate))+geom_line()+
#     scale_x_date(date_breaks = "2 weeks", date_labels ="%d %b" )
# print(p)


#putting our data in ts format

ts1<- ts(data=rpr$new_vacc_rate, start =c(2021,100), frequency = 365.25)
plot.ts(ts1)

ts2<- ts(data=dpr$new_vacc_rate, start =c(2021,100), frequency = 365.25)
plot.ts(ts2)

ts3<- ts(data=rpo$new_vacc_rate, start =c(2021,100), frequency = 365.25)
plot.ts(ts3)

ts4<- ts(data=dpo$new_vacc_rate, start =c(2021,100), frequency = 365.25)
plot.ts(ts4)

ar1 <- auto.arima(ts1)
ar2 <- auto.arima(ts2)
ar3 <- auto.arima(ts3)
ar4 <- auto.arima(ts4)

# # plotting the residuals
plot.ts(ar1$residuals)
plot.ts(ar2$residuals)
plot.ts(ar3$residuals)
plot.ts(ar4$residuals)

#forecast the values for next 5 months
forecast1 <- forecast(ar1,h=350)
plot(forecast1)

forecast2 <- forecast(ar2,h=350)
plot(forecast2)

forecast3 <- forecast(ar3,h=350)
plot(forecast3)

forecast4 <- forecast(ar4,h=350)
plot(forecast4)
```
Plots & exploratory data analysis

```{r}
# 
# # Sample data and plots for CO
# 
# colorado_data <- subset(election_2020, state == 'COLORADO')
# colorado_data_counties_won <- subset(election_2020_counties_won, state == 'COLORADO')
# 
# candidate_votes_co <- ggplot(data = colorado_data, aes(x = candidate, y = candidatevotes)) +
#   geom_col() +
#   scale_y_continuous(labels = scales::comma) +
#   scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
#   ggtitle('Votes per Candidate in CO')
# 
# county_candidate_co <- ggplot(data = colorado_data_counties_won, aes(candidate)) +
#   geom_bar() +
#   ggtitle('CO Counties per Candidate')
# 
# 
# figure <- ggarrange(candidate_votes_co, county_candidate_co,
#                     labels = c("1", "2"),
#                     ncol = 2, nrow = 1)
# #figure
# 
# # Add % of voter turnout per county plot?
# 
# 
# #Visualizing the vaccination rates in selected counties
# tscounty.final %>%
#   filter(combined %in% sample.county) %>%
#   ggplot(aes(x = date, y = actuals.vaccinationsCompleted, group = combined, color = combined)) +
#   geom_line(size = 1.25) +
#   facet_wrap(~combined, scales = 'free_y', ncol = 3) +
#   theme(legend.position = 'none') +
#   labs(color = '', x = 'Month', y = 'Cumulative Vaccinations By County') +
#   scale_color_brewer(type = 'qual', palette = 'Paired')
# 
# # Creating an interactive plot using plotly
# p <- ggplot2::last_plot() +
#   geom_line(size = 0.75) + # modifying the plot for plotly
#   theme_bw(base_size = 9) +
#   theme(legend.position = 'none') # to make margins smaller
# ggplotly(p, height = 900)
# 
# #fig <- plotly_build(p)
# #fig
# 
# ```
# 
# Time Series Analysis
# 
# ```{r}
# count_vaccine_col <- subset(count_vaccine, state.x == 'COLORADO')
# count_vaccine_col$date <- as.character.Date(count_vaccine_col$date)
# count_vaccine_col <- na.omit(count_vaccine_col)
# min_date <- min(count_vaccine_col$date)
# max_date <- max(count_vaccine_col$date)
# #count_vaccine_col_mat <- matrix(count_vaccine_col)
# first_ts <- ts(count_vaccine_col$actuals.cases)#, start=min_date, end=max_date, frequency = 365.25)
# #first_ts
# 
# plot.ts(first_ts)
# ```
# getting the census data
# 
# ```{r}
# plot(count_vaccine_col$actuals.cases)
# ```
# 
# ```{r}
# census_education <- read.csv('education/data.csv', header = TRUE, sep = ",", skip = 1)
# names(census_education)
# ```
# ```{r}
# census_income <- read.csv('income/data.csv', header = TRUE, sep = ",", skip = 1)
# names(census_income)
# ```
# 
# ```{r}
# census_race <- read.csv('race/data.csv', header = TRUE, sep = ",", skip = 1)
# names(census_race)
```
